[package]
name = "meta"
version = "0.1.0"
authors = ["shun-sfoo <ganymede0915@gmail>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
